<!DOCTYPE html>
<html lang="en">
<head>
	<link rel="favicon" href="/RSS/public/assets/images/favicon.png">
	<link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
<!--new -->
	<!-- <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
	<link href='http://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'> -->
<!--new -->
	<link rel="favicon" href="assets/images/favicon.png">

	<?php echo $this->headMeta(); ?>
	<?php echo $this->headTitle() ?>
	<?php echo $this->headLink() ?>
	
</head>

<body>
	<!-- Fixed navbar -->
	<div class="navbar navbar-inverse">
		<div class="container">
			<div class="navbar-header">
				<!-- Button for smallest screens -->
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
				<a class="navbar-brand" href="index.html">
					<img src="/RSS/public/assets/images/logo.png" alt="Techro HTML5 template"></a>
				</div>
				<div class="navbar-collapse collapse">
					<!-- Check for admin -->
					<ul class="nav navbar-nav pull-right mainNav">
						
						<li><a href="/RSS/public/rss/index">Home</a></li>
						<li><a href="/RSS/public/rss/add">Add RSS</a></li>
						
					</ul>
				</div>
				<!--/.nav-collapse -->
			</div>
		</div>
		<!-- /.navbar -->

		<header id="head" class="secondary">
			<div class="container">
				<div class="row">
					<div class="col-sm-8">
						<h1>RSS Site</h1>
					</div>
				</div>
			</div>
		</header>

		<?php echo $this->headScript() ?>	
		<!-- contents -->
	<!-- 	<ul class="nav nav-pills nav-stacked  col-xs-4 col-md-2" height="100" >
		    <li role="presentation" class="active"><a href="http://127.0.0.1/RSS/public/Admin">manage users</a></li>
		    <li role="presentation" class="active"><a href="http://127.0.0.1/RSS/public/Course">manage courses</a></li>
		    <li role="presentation" class="active"><a href="http://127.0.0.1/RSS/public/Category">manage categories</a></li>
		     <li role="presentation" class="active"><a href="http://127.0.0.1/RSS/public/Material">manage materials</a></li>
		</ul> -->


		<?php echo $this->layout()->content; ?>
		<!-- /contents -->

		<footer id="footer">
			<div class="container">
				<div class="social text-center">
					<a href="#"><i class="fa fa-twitter"></i></a>
					<a href="#"><i class="fa fa-facebook"></i></a>
					<a href="#"><i class="fa fa-dribbble"></i></a>
					<a href="#"><i class="fa fa-flickr"></i></a>
					<a href="#"><i class="fa fa-github"></i></a>
				</div>

				<div class="clear"></div>
				<!--CLEAR FLOATS-->
			</div>
			<div class="footer2">
				<div class="container">
					<div class="row">

						<div class="col-md-6 panel">
							<div class="panel-body">
								<p class="simplenav">
									<a href="index.html">Home</a> | 
									<a href="profile.html">Profile</a> |
									<a href="courses.html">Courses</a> |
									<a href="login.html">Login</a> |
									<a href="register.html">Register</a> |
								</p>
							</div>
						</div>

						<div class="col-md-6 panel">
							<div class="panel-body">
								<p class="text-right">
									Copyright &copy; 2014. Template by <a href="http://webthemez.com/" rel="develop">WebThemez.com</a>
								</p>
							</div>
						</div>

					</div>
					<!-- /row of panels -->
				</div>
			</div>
		</footer>

		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
		<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>

		<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.13.1/jquery.validate.min.js"></script>-->
		<!-- <script src="assets/js/custom.js"></script> -->

		<!--<script src="assets/js/login.js" type="text/javascript" charset="utf-8"async defer></script>-->
	

</body>
</html>


